// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fx_backend.Data;

#nullable disable

namespace fx_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250509143339_CreateMaterialsTable")]
    partial class CreateMaterialsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fx_backend.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SpecificHeat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaterialType = "Water",
                            SpecificHeat = 4.1840000000000002
                        },
                        new
                        {
                            Id = 2,
                            MaterialType = "Wood",
                            SpecificHeat = 1.76
                        },
                        new
                        {
                            Id = 3,
                            MaterialType = "Glass",
                            SpecificHeat = 0.83999999999999997
                        },
                        new
                        {
                            Id = 4,
                            MaterialType = "Silica",
                            SpecificHeat = 0.82999999999999996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
